package com.ob.view;

import com.ob.model.Cia;
import com.ob.view.panel.PnlAcceso;
import com.ob.view.panel.PnlLoginContainer;
import com.ob.view.panel.PnlAtencion;
import com.ob.view.panel.PnlMonitor;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author jc
 */
public final class FrmContainer extends FrmBase {

    private final Map<String, JPanel> cards = new HashMap<>();

    public FrmContainer(Cia cia) {
        super();
        initComponents();
        //setCards();
        //for (String key : cards.keySet()) {
            //System.out.println("Clave: " + key + " -> Valor: " + cards.get(key));
            //pnlContenedor.add(key, cards.get(key));
        //}
        pnlContenedor.add("Acceso", new PnlAcceso());
        pnlContenedor.add("Login", new PnlLoginContainer());
        pnlContenedor.add("Pedido", new PnlAtencion());
        
        lblEmpresa.setText(cia.getRazonSocial());
        lblCajero.setText("");
    }

    /*public void setCards() {
        cards.put("Acceso", new PnlAcceso());
        cards.put("Login", new PnlLoginContainer());
        cards.put("Pedido", new PnlPedido());
    }*/

    public static JPanel getContainer() {
        return pnlContenedor;
    }

    public static JLabel getLblCajero() {
        return lblCajero;
    }
    
    public static PnlMonitor getMonitor(){
        return pnlMonitor;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlCabecera = new javax.swing.JPanel();
        lblOB = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        lblCajero = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();
        pnlMonitor = new com.ob.view.panel.PnlMonitor();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlCabecera.setBackground(new java.awt.Color(20, 104, 162));
        pnlCabecera.setForeground(new java.awt.Color(20, 104, 162));
        pnlCabecera.setMinimumSize(new java.awt.Dimension(484, 35));
        pnlCabecera.setPreferredSize(new java.awt.Dimension(484, 35));
        pnlCabecera.setLayout(new java.awt.GridBagLayout());

        lblOB.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblOB.setForeground(new java.awt.Color(255, 255, 255));
        lblOB.setText("OPENBUSINESS");
        lblOB.setMinimumSize(new java.awt.Dimension(200, 15));
        lblOB.setPreferredSize(new java.awt.Dimension(200, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        pnlCabecera.add(lblOB, gridBagConstraints);

        lblEmpresa.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpresa.setText("EMPRESA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        pnlCabecera.add(lblEmpresa, gridBagConstraints);

        lblCajero.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblCajero.setForeground(new java.awt.Color(255, 255, 255));
        lblCajero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCajero.setText("CAJERO");
        lblCajero.setMinimumSize(new java.awt.Dimension(200, 15));
        lblCajero.setPreferredSize(new java.awt.Dimension(200, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        pnlCabecera.add(lblCajero, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(pnlCabecera, gridBagConstraints);

        pnlContenedor.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(pnlContenedor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 20;
        getContentPane().add(pnlMonitor, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel lblCajero;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblOB;
    private javax.swing.JPanel pnlCabecera;
    private static javax.swing.JPanel pnlContenedor;
    private static com.ob.view.panel.PnlMonitor pnlMonitor;
    // End of variables declaration//GEN-END:variables
}
