package com.ob.view;

import com.ob.model.Cia;
import com.ob.view.panel.PnlAcceso;
import com.ob.view.panel.PnlLogin;
import com.ob.view.panel.PnlPedido;

/**
 *
 * @author jc
 */
public class FrmContainer extends FrmBase {

    public FrmContainer(Cia cia) {
        super();
        initComponents();
        pnlContenedor.add("Acceso", new PnlAcceso());
        pnlContenedor.add("Login", new PnlLogin());
        pnlContenedor.add("Pedido", new PnlPedido());
        //Util.e(cia.getRazonSocial());
        lblEmpresa.setText(cia.getRazonSocial());
        lblUsuario.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlCabecera = new javax.swing.JPanel();
        lblOB = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlCabecera.setBackground(new java.awt.Color(20, 104, 162));
        pnlCabecera.setForeground(new java.awt.Color(20, 104, 162));
        pnlCabecera.setMinimumSize(new java.awt.Dimension(484, 35));
        pnlCabecera.setPreferredSize(new java.awt.Dimension(484, 35));
        pnlCabecera.setLayout(new java.awt.GridBagLayout());

        lblOB.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblOB.setForeground(new java.awt.Color(255, 255, 255));
        lblOB.setText("OPENBUSINESS");
        lblOB.setMinimumSize(new java.awt.Dimension(200, 15));
        lblOB.setPreferredSize(new java.awt.Dimension(200, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        pnlCabecera.add(lblOB, gridBagConstraints);

        lblEmpresa.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpresa.setText("EMPRESA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        pnlCabecera.add(lblEmpresa, gridBagConstraints);

        lblUsuario.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("USUARIO");
        lblUsuario.setMinimumSize(new java.awt.Dimension(200, 15));
        lblUsuario.setPreferredSize(new java.awt.Dimension(200, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        pnlCabecera.add(lblUsuario, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(pnlCabecera, gridBagConstraints);

        pnlContenedor.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(pnlContenedor, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblOB;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
