package com.ob.view.panel;

import com.ob.view.comp.LblCajero;
import com.ob.controller.UsuarioController;
import com.ob.model.Usuario;
import com.ob.util.Conn;
import com.ob.util.Util;
import java.sql.SQLException;
import java.util.List;

public class PnlAcceso extends javax.swing.JPanel {

    public PnlAcceso() {
        initComponents();
        
        try {
            List<Usuario> cajeros = new UsuarioController(Conn.getConnection()).getUsuarios(UsuarioController.ROL_CAJERO);
            LblCajero lblCajero;
            for (Usuario cajero : cajeros) {
                lblCajero = new LblCajero(cajero);
                add(lblCajero);
            }
        } catch (SQLException ex) {
            Util.e(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
