package com.ob.view.panel;

import com.ob.controller.AtencionController;
import com.ob.model.Atencion;
import com.ob.ticket.Imprimir;
import com.ob.util.App;
import com.ob.util.Conn;
import com.ob.util.Util;
import com.ob.view.FrmContainer;
import com.ob.view.comp.BtnOption;
import com.ob.view.table.TblAtencion;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author jc
 */
public class PnlAtencion extends javax.swing.JPanel {
    
    private final PnlEditarAtencion pnlEditarAtencion;
    
    public PnlAtencion() {
        initComponents();
        pnlEditarAtencion = new PnlEditarAtencion(pnlBuscar);
        PnlPagar pnlPagar = new PnlPagar(pnlBuscar);
        pnlBuscar.add("Producto", new PnlProducto());
        pnlBuscar.add("Editar", pnlEditarAtencion);
        pnlBuscar.add("Pagar", pnlPagar);
    }
    
    public static void setAtencion(int numero){
        try {
            List<Atencion> atencion = new AtencionController(Conn.getConnection()).getAtencion(numero);
            tblAtencion.setAtencion(atencion);
            App.CURRENT_ATENCION = numero;
            Util.changeCard(pnlBuscar, "Producto");
        } catch (SQLException ex) {
            Logger.getLogger(PnlAtencion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static TblAtencion getTable(){
        return tblAtencion;
    }
    
    private void editAtencion() {
        Atencion a = tblAtencion.getSelected();
        pnlEditarAtencion.setAtencion(a);
        Util.changeCard(pnlBuscar, "Editar");
    }
    
    public static JLabel getLblCount() {
        return lblCount;
    }
    
    public static BtnOption getLblMesa(){
        return btnMesa;
    }
    
    public static BtnOption getLblTotal(){
        return btnPagar;
    }
    
    public JPanel getPnlBuscar(){
        return pnlBuscar;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlLeft = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        JLabel1 = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnMesa = new com.ob.view.comp.BtnOption();
        btnPagar = new com.ob.view.comp.BtnOption();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAtencion = new com.ob.view.table.TblAtencion();
        pnlRight = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBuscarProducto = new com.ob.view.comp.BtnOption();
        btnPrecuenta = new com.ob.view.comp.BtnOption();
        lblOption8 = new com.ob.view.comp.BtnOption();
        pnlBuscar = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 2));

        pnlLeft.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(App.COLOR_HOLO_ORANGE_DARK);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        JLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        JLabel1.setForeground(new java.awt.Color(255, 255, 255));
        JLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JLabel1.setText("TOTAL ITEMS:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel3.add(JLabel1, gridBagConstraints);

        lblCount.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCount.setForeground(new java.awt.Color(255, 255, 255));
        lblCount.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel3.add(lblCount, gridBagConstraints);

        pnlLeft.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        btnMesa.setBackground(App.COLOR_HOLO_ORANGE_LIGHT);
        btnMesa.setText("P: 1");
        btnMesa.setMinimumSize(new java.awt.Dimension(50, 60));
        btnMesa.setPreferredSize(new java.awt.Dimension(50, 60));
        btnMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMesaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        jPanel4.add(btnMesa, gridBagConstraints);

        btnPagar.setBackground(App.COLOR_HOLO_RED_LIGHT);
        btnPagar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPagar.setText("S/. 0.00");
        btnPagar.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnPagar.setMinimumSize(new java.awt.Dimension(50, 60));
        btnPagar.setPreferredSize(new java.awt.Dimension(50, 60));
        btnPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagarMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.8;
        jPanel4.add(btnPagar, gridBagConstraints);

        pnlLeft.add(jPanel4, java.awt.BorderLayout.NORTH);

        tblAtencion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAtencionMouseClicked(evt);
            }
        });
        tblAtencion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblAtencionKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblAtencion);

        pnlLeft.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(pnlLeft);

        pnlRight.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ob/images/ic_action_search.png"))); // NOI18N
        btnBuscarProducto.setMinimumSize(new java.awt.Dimension(50, 60));
        btnBuscarProducto.setPreferredSize(new java.awt.Dimension(50, 60));
        btnBuscarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarProductoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(btnBuscarProducto, gridBagConstraints);

        btnPrecuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ob/images/precuenta.png"))); // NOI18N
        btnPrecuenta.setMinimumSize(new java.awt.Dimension(50, 60));
        btnPrecuenta.setPreferredSize(new java.awt.Dimension(50, 60));
        btnPrecuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrecuentaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(btnPrecuenta, gridBagConstraints);

        lblOption8.setText("S/.");
        lblOption8.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblOption8.setMinimumSize(new java.awt.Dimension(50, 60));
        lblOption8.setPreferredSize(new java.awt.Dimension(50, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(lblOption8, gridBagConstraints);

        pnlRight.add(jPanel2, java.awt.BorderLayout.NORTH);

        pnlBuscar.setLayout(new java.awt.CardLayout());
        pnlRight.add(pnlBuscar, java.awt.BorderLayout.CENTER);

        add(pnlRight);
    }// </editor-fold>//GEN-END:initComponents

    private void tblAtencionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAtencionMouseClicked
        editAtencion();
    }//GEN-LAST:event_tblAtencionMouseClicked

    private void tblAtencionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblAtencionKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_UP || evt.getKeyCode()==KeyEvent.VK_DOWN){
            editAtencion();
        }
    }//GEN-LAST:event_tblAtencionKeyReleased

    private void btnBuscarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProductoMouseClicked
        Util.changeCard(pnlBuscar, "Producto");
    }//GEN-LAST:event_btnBuscarProductoMouseClicked

    private void btnMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMesaMouseClicked
        FrmContainer.getMonitor().setVisible(!FrmContainer.getMonitor().isVisible());
    }//GEN-LAST:event_btnMesaMouseClicked

    private void btnPrecuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrecuentaMouseClicked
        Util.i(App.CURRENT_ATENCION);
        new Imprimir().precuenta(App.CURRENT_ATENCION);
    }//GEN-LAST:event_btnPrecuentaMouseClicked

    private void btnPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagarMouseClicked
        if(tblAtencion.getDtm().getRowCount()>0){
            Util.changeCard(pnlBuscar, "Pagar");
        }
    }//GEN-LAST:event_btnPagarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private com.ob.view.comp.BtnOption btnBuscarProducto;
    private static com.ob.view.comp.BtnOption btnMesa;
    private static com.ob.view.comp.BtnOption btnPagar;
    private com.ob.view.comp.BtnOption btnPrecuenta;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel lblCount;
    private com.ob.view.comp.BtnOption lblOption8;
    private static javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private static com.ob.view.table.TblAtencion tblAtencion;
    // End of variables declaration//GEN-END:variables
}
