package com.ob.view.panel;

import com.ob.controller.AtencionController;
import com.ob.model.Atencion;
import com.ob.util.App;
import com.ob.util.Conn;
import com.ob.view.table.TblPedido;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jc
 */
public class PnlPedido extends javax.swing.JPanel {
            
    public PnlPedido() {
        initComponents();
        pnlBuscar.add("PnlProducto", new PnlProducto());
    }
    
    public static void setAtencion(int numero){
        try {
            List<Atencion> atencion = new AtencionController(Conn.getConnection()).getAtencion(numero);
            tblPedido.setAtencion(atencion);
            App.CURRENT_ATENCION = numero;
        } catch (SQLException ex) {
            Logger.getLogger(PnlPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static TblPedido getTable(){
        return tblPedido;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlLeft = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblOption7 = new com.ob.util.LblOption();
        lblTotal = new com.ob.util.LblOption();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new com.ob.view.table.TblPedido();
        pnlRight = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblOption3 = new com.ob.util.LblOption();
        lblOption6 = new com.ob.util.LblOption();
        lblOption8 = new com.ob.util.LblOption();
        pnlBuscar = new javax.swing.JPanel();

        setBorder(null);
        setLayout(new java.awt.GridLayout(1, 2));

        pnlLeft.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(App.COLOR_HOLO_RED_LIGHT);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("TOTAL ITEMS:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel3.add(jLabel2, gridBagConstraints);

        pnlLeft.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel4.setBorder(null);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        lblOption7.setBackground(App.COLOR_HOLO_ORANGE_LIGHT);
        lblOption7.setText("P: 1");
        lblOption7.setMinimumSize(new java.awt.Dimension(50, 60));
        lblOption7.setPreferredSize(new java.awt.Dimension(50, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(lblOption7, gridBagConstraints);

        lblTotal.setBackground(App.COLOR_HOLO_RED_LIGHT);
        lblTotal.setText("S/. 0.00");
        lblTotal.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTotal.setMinimumSize(new java.awt.Dimension(50, 60));
        lblTotal.setPreferredSize(new java.awt.Dimension(50, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(lblTotal, gridBagConstraints);

        pnlLeft.add(jPanel4, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(tblPedido);

        pnlLeft.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(pnlLeft);

        pnlRight.setBorder(null);
        pnlRight.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(null);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblOption3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ob/images/ic_action_search.png"))); // NOI18N
        lblOption3.setMinimumSize(new java.awt.Dimension(50, 60));
        lblOption3.setPreferredSize(new java.awt.Dimension(50, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(lblOption3, gridBagConstraints);

        lblOption6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ob/images/precuenta.png"))); // NOI18N
        lblOption6.setMinimumSize(new java.awt.Dimension(50, 60));
        lblOption6.setPreferredSize(new java.awt.Dimension(50, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(lblOption6, gridBagConstraints);

        lblOption8.setText("S/.");
        lblOption8.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblOption8.setMinimumSize(new java.awt.Dimension(50, 60));
        lblOption8.setPreferredSize(new java.awt.Dimension(50, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(lblOption8, gridBagConstraints);

        pnlRight.add(jPanel2, java.awt.BorderLayout.NORTH);

        pnlBuscar.setBorder(null);
        pnlBuscar.setLayout(new java.awt.CardLayout());
        pnlRight.add(pnlBuscar, java.awt.BorderLayout.CENTER);

        add(pnlRight);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.ob.util.LblOption lblOption3;
    private com.ob.util.LblOption lblOption6;
    private com.ob.util.LblOption lblOption7;
    private com.ob.util.LblOption lblOption8;
    private com.ob.util.LblOption lblTotal;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private static com.ob.view.table.TblPedido tblPedido;
    // End of variables declaration//GEN-END:variables
}
