package com.ob.view.comp;

import com.ob.util.App;

import java.awt.GridBagConstraints;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Jimbert
 */
public class PnlTecladoNumericoOld extends javax.swing.JPanel {

    /** Creates new form PnlTecladoNumerico */
    public PnlTecladoNumericoOld() {
        initComponents();
        create(new JTextField());
    }

    public PnlTecladoNumericoOld(JTextField txtNumero) {
        initComponents();
        create(txtNumero);
    }
    
    private void create(JTextField txtNumero){
        LblBotonNumero[] lblBotonNumero = new LblBotonNumero[11];
        GridBagConstraints gbc;
        for (int i = 0; i < lblBotonNumero.length; i++) {
            if (i < lblBotonNumero.length - 1) {
                lblBotonNumero[i] = new LblBotonNumero(i + "", txtNumero);
                lblBotonNumero[i].setToolTipText(i + "");
            } else {
                lblBotonNumero[i] = new LblBotonNumero("", txtNumero);
                lblBotonNumero[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ob/clean.png")));
                lblBotonNumero[i].setToolTipText("Limpiar");
            }
        }
        int i = 0;
        for (int y = 0; y <= 3; y++) {
            if (y < 3) {
                for (int x = 0; x <= 2; x++) {

                    gbc = new GridBagConstraints();
                    gbc.gridx = x;
                    gbc.gridy = y;
                    gbc.gridwidth = 1;
                    gbc.fill = GridBagConstraints.BOTH;
                    gbc.weightx = 1.0;
                    gbc.weighty = 1.0;
                    add(lblBotonNumero[i + 1], gbc);
                    i += 1;
                }
            } else {
                gbc = new GridBagConstraints();
                gbc.gridx = 0;
                gbc.gridy = y;
                gbc.gridwidth = 2;
                gbc.fill = GridBagConstraints.BOTH;
                gbc.weightx = 1.0;
                gbc.weighty = 1.0;
                add(lblBotonNumero[0], gbc);
                break;
            }
        }
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.gridwidth = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        add(lblBotonNumero[10], gbc);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    class LblBotonNumero extends JLabel implements MouseListener {

        private JTextField txtNumero;

        public LblBotonNumero(String name, JTextField txtNumero) {
            super(name);
            this.txtNumero = txtNumero;
            setOpaque(true);
            setBackground(new java.awt.Color(0xffcccccc));
            setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            setFont(new java.awt.Font("Tahoma", 0, 24));
            setForeground(new java.awt.Color(0, 0, 0));
            setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            addMouseListener(this);
        }

        @Override
        public void mouseClicked(MouseEvent e) {
            // TODO Implement this method
            JLabel label = (JLabel) e.getSource();
            if(label.getToolTipText().equals("Limpiar")) {
                this.txtNumero.setText("");
            } else {
                this.txtNumero.setText(this.txtNumero.getText().concat(label.getText()));
            }
        }

        @Override
        public void mousePressed(MouseEvent e) {
            // TODO Implement this method
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            // TODO Implement this method
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            setForeground(App.COLOR_HOLO_RED_DARK);
        }

        @Override
        public void mouseExited(MouseEvent e) {
            setForeground(new java.awt.Color(0, 0, 0));
        }
    }
}
